name: shopease_admin
description: "ShopEase - E-commerce Admin Panel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Chart package for data visualization
  fl_chart: ^0.66.2

  # Internationalization
  intl: ^0.17.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets configuration (add this section)
  assets:
    - assets/images/123.png

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/OpenSans-Regular.ttf
#        - asset: assets/fonts/OpenSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700